@startuml

title COTOBA Talk rename room

Android -> Appsync:subscribeRoomUpdate
Android -> Android:ルーム名変更
Android -> Appsync:muteteRoomRename(RoomName)
Appsync -> DB:RoomName更新
DB -> lambda
lambda -> slack:Room名変更
lambda <-- slack:slackRoomId
lambda -> DB:slackRoomId更新
DB -> Appsync:ルーム情報リスト
Appsync --> Android:RoomUpdateCallback
Android -> Android:ルーム情報更新、名前変更時はRoomに画面遷移

@enduml