@startuml

title COTOBA Talk delete room ng from slack

Android -> Appsync:subscribeRoomUpdate
Android -> Android:ルーム削除
Android -> Appsync:muteteRoomDelete(RoomName)
Appsync -> lambda:ルーム削除
lambda -> slack:チャンネル削除
slack -> lambda:NG
lambda -> Appsync:NG
Appsync --> Android:RoomUpdateCallback
Android -> Android:ルーム情報更新、削除実施時はRoomsに画面遷移

@enduml